<?php
echo '<div class="wrap">';
	echo '<h2>Dynamic Page Content Instruction</h2>';

?>
	<p>
	    This Plugin "Dynamic Page Content" was created to build WordPress Pages with dynamic content that is generated by URL parameters. It's main purpose is to 
	    create Google AdWords Ads with landingpages containing parameters in this form: yourwebsite.com/some-directory/?prmtr=VALUE<br>
	    You can use this shortcode [DynamicPageContent] to output VALUE from the anywhere you want on a WordPress page. With this method you can create a very high number 
	    of Google AdWords Ads with automatically created and very compelling content for a very high conversion rate.
	</p>
</div>

